---

- name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled"
  block:
      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install cramfs(\\s|$)"
            line: "install cramfs /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Remove cramfs module"
        modprobe:
            name: cramfs
            state: absent
  when:
      - amazon2cis_rule_1_1_1_1
      - ansible_connection != 'docker'
  tags:
      - level1
      - automated
      - patch
      - rule_1.1.1.1
      - cramfs
      - modprobe

- name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled"
  block:
      - name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install squashfs(\\s|$)"
            line: "install squashfs /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.2 | PATCH | Ensure mounting of cramfs filesystems is disabled | Remove squashfs module"
        modprobe:
            name: squashfs
            state: absent
  when:
      - amazon2cis_rule_1_1_1_2
      - ansible_connection != 'docker'
  tags:
      - level1
      - automated
      - patch
      - rule_1.1.1.2
      - squashfs
      - modprobe

- name: "1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled"
  block:
      - name: "1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install udf(\\s|$)"
            line: "install udf /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.3 | PATCH | Remove udf module"
        modprobe:
            name: udf
            state: absent
  when:
      - amazon2cis_rule_1_1_1_3
      - ansible_connection != 'docker'
  tags:
      - level1
      - automated
      - patch
      - rule_1.1.1.3
      - udf
      - modprobe

# 1.6.1.6 Ensure no unconfined daemons exist (Scored)

- name: 1.6.1.6 Ensure no unconfined daemons exist (Scored)
  script: "{{ role_path }}/audit_1.6.1.6.sh"
  check_mode: no
  changed_when: False
  register: audit_1_6_1_6
  tags:
    - level-1
    - section-6
    - "1.6.1.6"
    - scored

- name: 1.6.1.6 Ensure no unconfined daemons exist (Scored)
  fail:
    msg: "{{ audit_1_6_1_6.stdout_lines }}"
  when:
    - audit_1_6_1_6.stdout_lines is defined and audit_1_6_1_6.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "1.6.1.6"
    - scored

- name: 1.6.1.6 Ensure no unconfined daemons exist (Scored)
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_1_6_1_6.stdout }}"
  when:
    - audit_1_6_1_6.stdout_lines is defined and audit_1_6_1_6.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "1.6.1.6"
    - scored
