---

- name: "3.5.2.1 | PATCH | Ensure nftables is installed"
  package:
      name: nftables
      state: present
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_3_5_2_1
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.2.1
      - firewall
      - nftables

- name: "3.5.2.2 | PATCH | Ensure firewalld is either not installed or masked with nftables"
  package:
      name: firewalld
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_3_5_2_2
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.2.2
      - firewall
      - nftables

- name: "3.5.2.3 | PATCH | Ensure iptables-services package is not installed"
  package:
      name: iptables-services
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_3_5_2_3
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.2.3
      - firewall
      - nftables

- name: "3.5.2.4 | PATCH | Ensure iptables are flushed"
  block:
      - name: "3.5.2.4 | PATCH | Ensure iptables are flushed | Flush IPv4 tables"
        command: iptables -F

      - name: "3.5.2.4 | PATCH | Ensure iptables are flushed | Flush IPv6 tables"
        command: ip6tables -F
        when:
            - amazon2cis_ipv6_required
  when:
      - amazon2cis_firewall != "iptables"
      - amazon2cis_rule_3_5_2_4
  tags:
      - level1
      - manual
      - patch
      - rule_3.5.2.4
      - firewall
      - nftables

- name: "3.5.2.5 | PATCH | Ensure a table exists"
  block:
      - name: "3.5.2.5 | AUDIT | Ensure a table exists | Check for tables"
        command: nft list tables
        changed_when: false
        failed_when: false
        register: amazon2cis_3_5_2_4_nft_tables

      - name: "3.5.2.5 | AUDIT | Ensure a table exists | Show existing tables"
        debug:
            msg:
                - "Below are the current nft tables, please review"
                - "{{ amazon2cis_3_5_2_5_nft_tables.stdout_lines }}"
        when:
            - amazon2cis_3_5_2_5_nft_tables.stdout | length > 0

      - name: "3.5.2.5 | AUDIT | Ensure a table exists | Alert on no tables"
        debug:
            msg:
                - "Warning! You currently have no nft tables, please review your setup"
                - 'Use the command "nft create table inet <table name>" to create a new table'
        when:
            - amazon2cis_3_5_2_5_nft_tables.stdout | length == 0
            - not amazon2cis_nft_tables_autoNewTable

      - name: "3.5.2.5 | PATCH | Ensure a table exists | Create table if needed"
        command: nft create table inet "{{ amazon2cis_nft_tables_tableName }}"
        failed_when: false
        when:
            - amazon2cis_nft_tables_autoNewTable
  when:
      - amazon2cis_rule_3_5_2_5
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.2.5
      - firewall
      - nftables

- name: "3.5.2.6 | PATCH | Ensure base chains exist"
  block:
      - name: "3.5.2.6 | AUDIT | Ensure base chains exist | Get current chains for INPUT"
        shell: nft list ruleset | grep 'hook input'
        changed_when: false
        failed_when: false
        register: amazon2cis_3_5_2_6_input_chains

      - name: "3.5.2.6 | AUDIT | Ensure base chains exist | Get current chains for FORWARD"
        shell: nft list ruleset | grep 'hook forward'
        changed_when: false
        failed_when: false
        register: amazon2cis_3_5_2_6_forward_chains

      - name: "3.5.2.6 | AUDIT | Ensure base chains exist | Get current chains for OUTPUT"
        shell: nft list ruleset | grep 'hook output'
        changed_when: false
        failed_when: false
        register: amazon2cis_3_5_2_6_output_chains

      - name: "3.5.2.6 | AUDIT | Ensure base chains exist | Display chains for review"
        debug:
            msg:
                - "Below are the current INPUT chains"
                - "{{ amazon2cis_3_5_2_6_input_chains.stdout_lines }}"
                - "Below are the current FORWARD chains"
                - "{{ amazon2cis_3_5_2_6_forward_chains.stdout_lines }}"
                - "Below are teh current OUTPUT chains"
                - "{{ amazon2cis_3_4_2_6_output_chains.stdout_lines }}"
        when:
            - not amazon2cis_nft_tables_autoChainCreate

      - name: "3.5.2.6 | PATCH | Ensure base chains exist | Create chains if needed"
        command: "{{ item }}"
        failed_when: false
        with_items:
            - nft create chain inet "{{ amazon2cis_nft_tables_tableName }}" input { type filter hook input priority 0 \; }
            - nft create chain inet "{{ amazon2cis_nft_tables_tableName }}" forward { type filter hook forward priority 0 \; }
            - nft create chain inet "{{ amazon2cis_nft_tables_tableName }}" output { type filter hook output priority 0 \; }
        when:
            - amazon2cis_nft_tables_autoChainCreate
  when:
      - amazon2cis_rule_3_5_2_6
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.2.6
      - skip_ansible_lint
      - firewall
      - nftables

- name: 3.5.1.2 - Ensure loopback traffic is configured(-i lo)
  iptables:
    chain: INPUT
    in_interface: "lo"
    jump: ACCEPT
  tags:
    - level-1
    - section-3
    - "3.5.1.2"
    - scored

- name: 3.5.1.2 - Ensure loopback traffic is configured(-o lo)
  iptables:
    chain: OUTPUT
    out_interface: "lo"
    jump: ACCEPT
  tags:
    - level-1
    - section-3
    - "3.5.1.2"
    - scored

- name: 3.5.1.2 - Ensure loopback traffic is configured(-i 127.0.0.1/8)
  iptables:
    chain: INPUT
    source: 127.0.0.0/8
    jump: DROP
  tags:
    - level-1
    - section-3
    - "3.5.1.2"
    - scored


- name: "3.5.2.8 | PATCH | Ensure outbound and established connections are configured"
  block:
      - name: "3.5.2.8 | AUDIT | Ensure outbound and established connections are configured | Gather incoming connection rules"
        shell: nft list ruleset | awk '/hook input/,/}/' | grep -E 'ip protocol (tcp|udp|icmp) ct state'
        changed_when: false
        failed_when: false
        register: amazon2cis_3_5_2_8_inconnectionrule

      - name: "3.5.2.8 | AUDIT | Ensure outbound and established connections are configured | Gather outbound connection rules"
        shell: nft list ruleset | awk '/hook output/,/}/' | grep -E 'ip protocol (tcp|udp|icmp) ct state'
        changed_when: false
        failed_when: false
        register: amazon2cis_3_5_2_8_outconnectionrule

      - name: "3.5.2.8 | PATCH | Ensure outbound and established connections are configured | Add input tcp established accpet policy"
        command: nft add rule inet "{{ amazon2cis_nft_tables_tableName }}" input ip protocol tcp ct state established accept
        when:
            - '"ip protocol tcp ct state established accept" not in amazon2cis_3_5_2_8_inconnectionrule.stdout'

      - name: "3.5.2.8 | PATCH | Ensure outbound and established connections are configured | Add input udp established accpet policy"
        command: nft add rule inet "{{ amazon2cis_nft_tables_tableName }}" input ip protocol udp ct state established accept
        when:
            - '"ip protocol udp ct state established accept" not in amazon2cis_3_5_2_8_inconnectionrule.stdout'

      - name: "3.5.2.8 | PATCH | Ensure outbound and established connections are configured | Add input icmp established accpet policy"
        command: nft add rule inet "{{ amazon2cis_nft_tables_tableName }}" input ip protocol icmp ct state established accept
        when:
            - '"ip protocol icmp ct state established accept" not in amazon2cis_3_5_2_8_inconnectionrule.stdout'

      - name: "3.5.2.8 | PATCH | Ensure outbound and established connections are configured | Add output tcp new, related, established accpet policy"
        command: nft add rule inet "{{ amazon2cis_nft_tables_tableName }}" output ip protocol tcp ct state new,related,established accept
        when:
            - '"ip protocol tcp ct state established,related,new accept" not in amazon2cis_3_5_2_8_outconnectionrule.stdout'

      - name: "3.5.2.8 | PATCH | Ensure outbound and established connections are configured | Add output udp new, related, established accpet policy"
        command: nft add rule inet "{{ amazon2cis_nft_tables_tableName }}" output ip protocol udp ct state new,related,established accept
        when:
            - '"ip protocol udp ct state established,related,new accept" not in amazon2cis_3_5_2_8_outconnectionrule.stdout'

      - name: "MANUAL| 3.5.2.8 | PATCH | Ensure outbound and established connections are configured | Add output icmp new, related, established accpet policy"
        command: nft add rule inet "{{ amazon2cis_nft_tables_tableName }}" output ip protocol icmp ct state new,related,established accept
        when:
            - '"ip protocol icmp ct state established,related,new accept" not in amazon2cis_3_5_2_8_outconnectionrule.stdout'
  when:
      - amazon2cis_rule_3_5_2_8
  tags:
      - level1
      - manual
      - patch
      - rule_3.5.2.8
      - firewall
      - nftables

- name: 3.5.1.1 - Ensure default deny firewall policy
  iptables:
    chain: "{{item}}"
    policy: DROP
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  tags:
    - level-1
    - section-3
    - "3.5.1.1"
    - scored

- name: "3.5.2.10 | PATCH | Ensure nftables service is enabled"
  systemd:
      name: nftables
      enabled: true
  when:
      - amazon2cis_rule_3_5_2_10
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.2.10
      - firewall
      - nftables

- name: "3.5.2.11 | PATCH | Ensure nftables rules are permanent"
  lineinfile:
      path: /etc/sysconfig/nftables.conf
      state: present
      insertafter: EOF
      line: include "/etc/nftables/inet-{{ amazon2cis_nft_tables_tableName }}"
  when:
      - amazon2cis_rule_3_5_2_11
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.2.11
      - firewall
      - nftables


- name: 3.5.1.1 - Ensure default deny firewall policy
  iptables:
    chain: "{{item}}"
    policy: DROP
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  tags:
    - level-1
    - section-3
    - "3.5.1.1"
    - scored
