---

- name: "5.4.1 | PATCH | Ensure password creation requirements are configured"
  lineinfile:
      path: /etc/security/pwquality.conf
      regexp: '^{{ item.key }}'
      line: '{{ item.key }} = {{ item.value }}'
  with_items:
      - { key: 'minlen', value: '14' }
      - { key: 'minclass', value: '4' }
  when:
      - amazon2cis_rule_5_4_1
  tags:
      - level1
      - automated
      - patch
      - rule_5.4.1
      - pamd

# 5.3.2 Ensure lockout for failed password attempts is configured

- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_faillock.so - before)
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments:
      - preauth
      - audit
      - silent
      - deny=5
      - "unlock_time={{ failed_password_attempt_lockout_time }}"
    state: before
  with_items:
  - system-auth
  - password-auth
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored

- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_faillock.so - last)
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: sufficient
    new_module_path: pam_faillock.so
    module_arguments:
      - authsucc
      - audit
      - deny=5
      - "unlock_time={{ failed_password_attempt_lockout_time }}"
    state: after
  with_items:
  - system-auth
  - password-auth
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored

- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_faillock.so - after)
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: "[default=die]"
    new_module_path: pam_faillock.so
    module_arguments:
      - authfail
      - audit
      - deny=5
      - "unlock_time={{ failed_password_attempt_lockout_time }}"
    state: after
  with_items:
  - system-auth
  - password-auth
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored

- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_unix.so)
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_control: '[success=1 default=bad]'
    module_arguments: ''
    state: updated
  with_items:
  - system-auth
  - password-auth
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored

- name: 5.4.4.1 - Ensure default user umask is 027 or more restrictive
  replace:
    regexp: '(^\s*umask) [0-9]{3}'
    replace: "umask {{ cis_umask_default }} # switched to {{ cis_umask_default }} by 5.4.4 of ansible-cis-amazon-linux-2"
    path: "{{ item }}"
  with_items: "{{ cis_umask_shell_files }}"
  tags:
    - level-1
    - section-5
    - "5.4.4"
    - scored

- name: 5.4.4.1 - Ensure default user umask is 027 or more restrictive in files under profile.d/
  replace:
    regexp: '(^\s*umask) [0-9]{3}'
    replace: "umask {{ cis_umask_default }} # switched to {{ cis_umask_default }} by 5.4.4 of ansible-cis-amazon-linux-2"
    path: "{{ item }}"
  with_fileglob: "{{ cis_umask_shell_additional_files_directory }}/*"
  tags:
    - level-1
    - section-5
    - "5.4.4"
    - scored

- name: 5.4.1.2 - Obtain a list of user accounts
  shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | cut -d: -f1"
  register: egrep_5_4_1_2
  check_mode: no
  changed_when: False
  tags:
    - level-1
    - section-5
    - "5.4.1.2"
    - scored

- name: 5.4.1.2 - Ensure minimum days between password changes is 7 or more
  lineinfile:
    dest: "/etc/login.defs"
    regexp: "^PASS_MIN_DAYS\\s+"
    line: "PASS_MIN_DAYS {{ cis_pass_min_days }}"
  tags:
    - level-1
    - section-5
    - "5.4.1.2"
    - scored

- name: 5.4.1.2 - Set minimum password change interval for all user accounts
  command: "chage --mindays {{ cis_pass_min_days }} {{ item }}"
  with_items: "{{ egrep_5_4_1_2.stdout_lines }}"
  tags:
    - level-1
    - section-5
    - "5.4.1.2"
    - scored

# 5.4.5 Ensure default user shell timeout is 900 seconds or less

- name: 5.4.5 - Ensure default user shell timeout is 900 seconds or less
  lineinfile:
    regexp: "^TMOUT"
    line: "TMOUT={{ cis_user_shell_timeout }}"
    dest: "{{ item }}"
  with_items: "{{ cis_umask_shell_files }}"
  tags:
    - level-2
    - section-5
    - "5.4.5"
    - scored
